### ISSUE TITLE
Problème de compilation

### ISSUE THREAD

**Issue by GuyliannEngels** [DahKawtar/kawtar-dahman-blog#1]
Bonjour @DahKawtar,

TU m'as contacté car tu avais un problème avec ton blog. Comme tu le sais maintenant, je préfère employer les ISSUES pour répondre aux problèmes des étudiants. 

Voici ta question/demande : 

Bonjour, j'ai un petit problème avec mon article pour l'anglais, quand je clique sur "knit" ça me fait ça et je n'arrive pas à savoir pourquoi. Pouvez vous m'aider s'il vous plaît ?

![20191017_120428](https://user-images.githubusercontent.com/33956170/67079157-f76ac680-f192-11e9-857d-a64cf7cf4e9a.jpg)

**Comment by GuyliannEngels** [comment]
Ce projet, tu le réalise sur ton compte GitHub et il t'appartient. Nous avons donc 2 solutions

1. Tu me donne accès à ton projet (settings, collaborateurs)

2. Je fork ton dépôt et te propose un PULL REQUEST à la suite de cela 

Je te laisse décider

**Comment by GuyliannEngels** [comment]
c'est corrigé :) 

J'ai trouvé tu as commis une erreur dans la date de ton fichier article1.Rmd La doit doit être renseigné comme cela 

- mm-dd-yyyy donc mois-jour-années

Tu avais encodée 

- dd-mm-yyyy 

Une petite erreur mais le programme est capricieux 

N'oublie pas de faire un PULL

**Comment by DahKawtar** [comment]
Oui c'était ça ! Vous aviez raison. Merci beaucoup ! Et en effet une toute petite erreur mais c'est réglé.
________________________________
De : Guyliann Engels <notifications@github.com>
Envoyé : vendredi 18 octobre 2019 12:27:38
À : DahKawtar/kawtar-dahman-blog <kawtar-dahman-blog@noreply.github.com>
Cc : Kawtar DAHMAN <Kawtar.DAHMAN@student.umons.ac.be>; Mention <mention@noreply.github.com>
Objet : Re: [DahKawtar/kawtar-dahman-blog] Problème de compilation (#1)


c'est corrigé :)

J'ai trouvé tu as commis une erreur dans la date de ton fichier article1.Rmd La doit doit être renseigné comme cela

  *   mm-dd-yyyy donc mois-jour-années

Tu avais encodée

  *   dd-mm-yyyy

Une petite erreur mais le programme est capricieux

N'oublie pas de faire un PULL
